### PR TITLE
feat: allow any string as model

### PR DESCRIPTION
**Pull request by XiaomaiTX**
refer: #365 

Allow any string as model

Nee to be review

Best regard.

### CODE REVIEW

**Comment by XiaomaiTX** [comment]
Hi, @di-sukharev 

refer to: #365

Best regards.

**Comment by XiaomaiTX** [comment]
Mark
@di-sukharev

**Review by di-sukharev — COMMENTED** [review]
could you also remove the enums with model names please

**Comment by XiaomaiTX** [comment]
yeap, I will do it later

**Comment by di-sukharev** [comment]
@XiaomaiTX please let me know when i can merge it, no rush <3

**Comment by XiaomaiTX** [comment]
Yeah I'm still in holiday, works will be done later

**Comment by di-sukharev** [comment]
@XiaomaiTX merged, will manage myself, thank you

**Pull request merged**
