### PR TITLE
Add E2E Testing for OpenCommit CLI in GitHub Actions

### PR DESCRIPTION
**Pull request by malpou**
This draft PR introduces end-to-end (E2E) tests for the OpenCommit CLI tool. The main goal of these tests is to simulate user interactions and ensure the tool functions as expected. 

Key Points:
- Tests are designed to be executed in GitHub Actions.
- These tests will be triggered on all new pull requests to ensure robustness before merging.

Currently facing some challenges with the tests. Looking forward to discussing and resolving them with @di-sukharev.

### CODE REVIEW

**Comment by di-sukharev** [comment]
@malpou it's an honour to be part of the team with you <3

let me know what help you need and i will do my best to assist

**Comment by malpou** [comment]
You too, it's a fun project you have made! 

I've started getting the tests to work locally (they still have some issues), but the blocker now is getting them to run consistent in the actions.
Currently I'm just getting a timeout on them, so something is hanging 🤷‍♂️

What are your thought of adding the `--test` flag that will just give us a generic test commit message instead of calling the API?

**Comment by di-sukharev** [comment]
@malpou 

why do you think we need `--test` flag? i guess mocking openAI api isnt working in GitHub action, right?

**Comment by di-sukharev** [comment]
@malpou hey brother, any blockers here i can help with?

**Comment by di-sukharev** [comment]
@malpou im finally back, do you still want to finish this PR?

**Comment by di-sukharev** [comment]
@malpou <3 ping me when you have time, tests is all we need :) please pull the latest dev to solve conflicts

**Comment by malpou** [comment]
Hi @di-sukharev 
I'm busy with other things at the moment so won't have time to finish this right now

**Comment by di-sukharev** [comment]
no worries man, thank you for all the contributions <3 <3 <3

**Pull request closed without merging**
