### PR TITLE
feat: Add support for extra args to be passed to the git commit command

### PR DESCRIPTION
**Pull request by nader-zouaoui**
As the name of the PR explains I added a few lines to support some extra arguments to be passed to the `git commit` command.

For example, say I want to execute git commit with `--no-verify` using oc I simply cannot do it,

What I added makes you able to do `oc --no-verify` and it  translates to `git commit -m ${generatedText} --no-verify`

### CODE REVIEW

**Comment by nader-zouaoui** [comment]
I could add a small doc section for it if approved

**Review by di-sukharev — APPROVED** [review]
smart smart :)

approved! could you add some docs to readme?

**Comment by nader-zouaoui** [comment]
Sure bro give me a minute

**Comment by nader-zouaoui** [comment]
@di-sukharev here's the [Doc](https://github.com/di-sukharev/opencommit/pull/17/commits/80ffd9e34563b33c130e7d304a565e9124396d65)

**Comment by di-sukharev** [comment]
@nader-zouaoui really awesome feature! could you solve the conflict pls and let's merge it

**Pull request merged**
