### PR TITLE
Add Gemini Pro support to CLI

### PR DESCRIPTION
**Pull request by drewpayment**
Added a new AI provider and enabled Google Gemini Pro support. Only added the Gemini Pro 1.0 model for now, but should be able to simply add to the models list if adopted. 

Added this issue: https://github.com/di-sukharev/opencommit/issues/308

### CODE REVIEW

**Comment by mitchross** [comment]
Consider adding a small readme note on how to generate Gemini API key.

**Comment by drewpayment** [comment]
> Consider adding a small readme note on how to generate Gemini API key.

Added notes to README.md.

**Comment by di-sukharev** [comment]
@drewpayment great job, could you run `npm run build` to fix the `/out` conflicts and look into other conflicts pls

**Comment by drewpayment** [comment]
Will do, I need to make a couple modifications to the prompt too because Gemini is hallucinating once in awhile.

**Comment by di-sukharev** [comment]
@drewpayment let me know when this is ready <3

**Comment by drewpayment** [comment]
I worked on it a little bit last night but I'm a bit perplexed because it keeps using the initial default prompt and writing commit details based on it. Trying to find the best way to undo that bit without impacting anything else.

**Comment by matt-degraffenreid** [comment]
Hey @drewpayment,

I actually work on Google's agent assist so I have some insight into your issue. The reason that's happening is because you need to give the model context, examples, and a message.

Screenshot 2024-03-20 at 7 37 36 AM
Screenshot 2024-03-20 at 7 37 50 AM
Screenshot 2024-03-20 at 7 38 01 AM
Screenshot 2024-03-20 at 7 38 12 AM

The implementation I used is also different I had to use @google-cloud/aiplatform and used application creds for auth. My result being this:

Screenshot 2024-03-20 at 7 43 03 AM

Try using this as your prompt and see if the issue resolves itself. If it does then structure the format like this going forward.

The freeform paragraph is the context, the first pair of input/output is the example, the second one is the message.
```
"""You are to act as the author of a commit message in git. Your mission is to create clean and comprehensive commit messages as per the conventional commit convention and explain WHAT were the changes and mainly WHY the changes were done. I\'ll send you an output of \'git diff --staged\' command, and you are to convert it into a commit message.
  You should only include the changes that are relevant to the commit. Do not include any changes that are not relevant to the commit.
  Do not preface the commit with anything. Conventional commit keywords:fix, feat, build, chore, ci, docs, style, refactor, perf, test.  
    Don\'t add any descriptions to the commit, only commit message.

input: diff --git a/src/server.ts b/src/server.ts
    index ad4db42..f3b18a9 100644
    --- a/src/server.ts
    +++ b/src/server.ts
    @@ -10,7 +10,7 @@
    import {
        initWinstonLogger();
        
        const app = express();
        -const port = 7799;
        +const PORT = 7799;
        
        app.use(express.json());
        
        @@ -34,6 +34,6 @@
        app.use((_, res, next) => {
            // ROUTES
            app.use(PROTECTED_ROUTER_URL, protectedRouter);
            
            -app.listen(port, () => {
                -  console.log(\\`Server listening on port \\${port}\\`);
                +app.listen(process.env.PORT || PORT, () => {
                    +  console.log(\\`Server listening on port \\${PORT}\\`);
                });
output: fix(server.ts): change port variable case from lowercase port to uppercase PORT to improve semantics
feat(server.ts): add support for process.env.PORT environment variable to be able to run app on a configurable port

input: index b6490b6..d50c82d 100755
--- a/out/cli.cjs
+++ b/out/cli.cjs
@@ -6,8 +6,8 @@ var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
 var __getOwnPropNames = Object.getOwnPropertyNames;
 var __getProtoOf = Object.getPrototypeOf;
 var __hasOwnProp = Object.prototype.hasOwnProperty;
-var __commonJS = (cb, mod) => function __require() {
-  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
output:
"""
```

The code I wrote was quick and dirty, it works for me but it's not in state to open a PR. Let me know if this doesn't fix your issue and I'll take a day or so to clean it up and open a PR on your repo.

**Comment by drewpayment** [comment]
Thanks for the notes, @matt-degraffenreid ! I haven't been able to work on cleaning this up this week yet, but I was hoping I would be able to just make the prompt changes directly in `gemini.ts`. I did notice I mistakenly committed my `pnpm-lock.yaml` as well. Planning to clean it up with the model fixes.

**Comment by di-sukharev** [comment]
let me know when i should take a look, merge and test it

**Comment by di-sukharev** [comment]
@drewpayment please run `npm run build` so the `/out` dir is not conflicting, hope it helps :)

**Comment by drewpayment** [comment]
This is still on my list! I will try to get it cleaned up and ready tonight.

**Comment by drewpayment** [comment]
Opened new PR #332

**Pull request closed without merging**
