### PR TITLE
Feat: Add Claude 3 support

### PR DESCRIPTION
**Pull request by metavind**
I have added Anthropic Claude 3 support for opencommit.

Issue #312

### CODE REVIEW

**Comment by di-sukharev** [comment]
great work! you should be merging to dev though :) let me know when i can merge it

**Review by di-sukharev — APPROVED** [review]

**Comment by di-sukharev** [comment]
@metavind hi, could you please look into failed checks <3

**Comment by metavind** [comment]
@di-sukharev update the dependencies. I'm not quite sure what changes would cause the e2e issue. From the log, it seems to be going to the else block here:

`if (remotes.length === 1 && config?.OCO_GITPUSH !== true) {
        const isPushConfirmedByUser = await confirm({
          message: 'Do you want to run `git push`?'
      .......
} else {
        const selectedRemote = (await select({
          message: 'Choose a remote to push to',
          options: remotes.map((remote) => ({ value: remote, label: remote }))
        })) as string;
        });`

**Comment by di-sukharev** [comment]
looks like `config?.OCO_GITPUSH` is null or undefined

this is wrong. `OCO_GITPUSH` is supposed to push without asking any of this prompts

**Comment by di-sukharev** [comment]
and looks like there is no remote or only one, it should be a 1 line fix, @metavind could you please look into it if you have time?

**Comment by metavind** [comment]
@di-sukharev I haven't made any changes to `OCO_GITPUSH` config so I think this isn't an issue related to the addition of anthropic claude models. The e2e tests seem to be broken, and a fix has been proposed in #321.

**Comment by matscube** [comment]
@di-sukharev @metavind 

I have fixed the E2E tests that were broken.
https://github.com/di-sukharev/opencommit/pull/321


The flow after commit has changed due to the addition of ```OCO_GITPUSH```, so I have changed the expected values in the tests.

### Note
Due to a bug in getConfig, the value of ```OCO_GITPUSH``` seems to change depending on the presence or absence of a global configuration file.
* If there is no global configuration file, ```OCO_GITPUSH``` is set to the value of the env file or the default ```true```.
* If there is a global configuration file and the ```OCO_GITPUSH``` key does not exist in the configuration file, ```OCO_GITPUSH``` seems to be ```undefined```.

In the getConfig method, only the keys in the configuration file are looped through at the following location, so the default values for keys not in the configuration file are being ignored and become undefined.


```typescript
// commands/config.ts
export const getConfig = (): ConfigType | null => {
  const configFromEnv = {
...
    OCO_GITPUSH: process.env.OCO_GITPUSH === 'false' ? false : true,
...
  };

  const configExists = existsSync(configPath);
  // when there is no global config file
  if (!configExists) return configFromEnv;

  const configFile = readFileSync(configPath, 'utf8');
  const config = iniParse(configFile);
 
  // HERE: The config variable only contains keys from the configuration file
  for (const configKey of Object.keys(config)) {
    if (
      ['null', 'undefined'].includes(config[configKey])
...
  }

  // when there is global config file
  return config;
...
```

**Comment by metavind** [comment]
@di-sukharev no worries! Done <3

**Pull request merged**
