### PR TITLE
feat: support pnpm

### PR DESCRIPTION
**Pull request by a1ooha**

### CODE REVIEW

**Comment by di-sukharev** [comment]
hi @a1ooha could you explain how this works and why needed?

**Comment by a1ooha** [comment]
> hi @a1ooha could you explain how this works and why needed?

If the project is using pnpm as the package manager, you can't find `@commitlint/load` through `node_modules/@commitlint/load/package.json`. The dependencies installed by pnpm are in the `node_modules/.pnpm` directory.

**Comment by a1ooha** [comment]
The output of `oco commitlint get` is `[object Object]`, there is no way to see the exact configuration.

**Comment by di-sukharev** [comment]
@a1ooha awesome, got it!

could you change the base to dev please, pull the latest dev, fix the conflicts if any and it will be deployed in the coming https://github.com/di-sukharev/opencommit/pull/397

**Review by di-sukharev — APPROVED** [review]

**Pull request merged**
