### PR TITLE
3.2.0

### PR DESCRIPTION
**Pull request by di-sukharev**

### CODE REVIEW

**Comment by matscube** [comment]
@di-sukharev 
I'm really grateful for this tool as a user, and I'm happy to be able to contribute as a developer.
I'm always looking forward to new features being added. 🎉

**Comment by di-sukharev** [comment]
@matscube deployed, please update and lmk if it works for you, there are some tricky migrations to the config happening as you can see in the code. i've deleted a lot of redundant config vars and made it simpler to support

**Comment by matscube** [comment]
@di-sukharev 
Thank you for the deployment!
I installed the latest version of oco(3.2.1) and tried it out a bit, and found some points that might be better to fix.

----

When I ran the `oco` command, the migration ran. (I may have had to run it a few times.)
```
$ oco
```
After running the migration, I ran `oco` and was instructed to set `OCO_AI_PROVIDER`, so I set it to `openai` with the config command.
```
$ oco config set OCO_AI_PROVIDER=openai
```
Also, the migration caused the API_KEY (OCO_OPENAI_API_KEY) setting to disappear, so I set OCO_API_KEY again.

When I ran the `oco` command again, I got an error about `max_tokens`.
```
$ oco

✖ 400 Invalid type for 'max_tokens': expected an integer, but got a string instead.
```

By migration, the following line will be automatically set in the global configuration file, but it seems that an error will occur if it is `undefined`.
```
OCO_TOKENS_MAX_OUTPUT=undefined
```
If you comment out the line of `OCO_TOKENS_MAX_OUTPUT`, `oco` can be executed.

----

It seems that an error occurs when `OCO_TOKENS_MAX_OUTPUT` is `undefined`. (`OCO_TOKENS_MAX_INPUT` was fine even if it was `undefined`)

By commenting out `OCO_TOKENS_MAX_OUTPUT` or deleting the setting itself from `.opencommit`, `oco` can be executed.
However, when the `oco config set` command is executed, if there is no setting for `OCO_TOKENS_MAX_OUTPUT`, `OCO_TOKENS_MAX_OUTPUT=undefined` will be automatically added, so the user needs to set the appropriate number for `OCO_TOKENS_MAX_OUTPUT` by themselves.

Some users might get in trouble.
It might be better to set the value of `OCO_TOKENS_MAX_OUTPUT` automatically set by the `oco config set` command to `500`, the default value, instead of `undefined`.

**Comment by di-sukharev** [comment]
i see, preparing the patch

**Comment by di-sukharev** [comment]
@matscube hmm.. i dont see this behaviour. for me `src/migrations/02_set_missing_default_values.ts` works correctly and sets the missing keys to their default values.

this is my config before migrations:
```
OCO_TOKENS_MAX_OUTPUT=undefined
OCO_MODEL=gpt-4o-mini
OCO_API_URL=undefined
OCO_OPENAI_API_KEY=my_key
OCO_AI_PROVIDER=openai
OCO_TOKENS_MAX_INPUT=undefined
OCO_DESCRIPTION=false
OCO_EMOJI=false
OCO_LANGUAGE=en
OCO_MESSAGE_TEMPLATE_PLACEHOLDER=$msg
OCO_PROMPT_MODULE=conventional-commit
OCO_ONE_LINE_COMMIT=false
OCO_TEST_MOCK_TYPE=commit-message
OCO_GITPUSH=true
```

this is the config after migrations were applied:
```
OCO_TOKENS_MAX_OUTPUT=4096
OCO_MODEL=gpt-4o-mini
OCO_API_URL=undefined
OCO_API_KEY=my_key
OCO_AI_PROVIDER=openai
OCO_TOKENS_MAX_INPUT=40960
OCO_DESCRIPTION=false
OCO_EMOJI=false
OCO_LANGUAGE=en
OCO_MESSAGE_TEMPLATE_PLACEHOLDER=$msg
OCO_PROMPT_MODULE=conventional-commit
OCO_ONE_LINE_COMMIT=false
OCO_TEST_MOCK_TYPE=commit-message
OCO_GITPUSH=true
```

**Comment by di-sukharev** [comment]
i reproduced the behaviour. thank you

**Comment by di-sukharev** [comment]
will be fixed here https://github.com/di-sukharev/opencommit/pull/414

**Comment by di-sukharev** [comment]
merged https://github.com/di-sukharev/opencommit/pull/413

**Pull request merged**
