### PR TITLE
390 add config set tests

### PR DESCRIPTION
**Pull request by di-sukharev**
solve https://github.com/di-sukharev/opencommit/issues/390 and refactor isCancel

### CODE REVIEW

**Comment by di-sukharev** [comment]
@matscube could you review please

**Comment by di-sukharev** [comment]
i dont understand [why the unit tests fail](https://github.com/di-sukharev/opencommit/actions/runs/10634567140/job/29482362930?pr=399) 🤔

**Comment by matscube** [comment]
@di-sukharev Hi, It seems that an error occurs when the cleanup function is executed for a directory that no longer exists.

For example, cleanup is executed in `beforeEach` and `afterEach`, but `globalConfigFile` / `envConfigFile` are set to the same path between each test (`it`) and test (`it`), so the same directory is cleaned up twice and an error occurs.

```typescript
  beforeEach(async () => {
    resetEnv(originalEnv);
    if (globalConfigFile) await globalConfigFile.cleanup();
    if (envConfigFile) await envConfigFile.cleanup();
  });

  afterEach(async () => {
    if (globalConfigFile) await globalConfigFile.cleanup();
    if (envConfigFile) await envConfigFile.cleanup();
  });

  describe(...
    it(...
    it(...
```


It can be fixed by changing the code to execute cleanup only once, but it seems easier to fix by checking the existence of the directory in the cleanup function.

I created a PR on this branch, so please check it out.
https://github.com/di-sukharev/opencommit/pull/401

**Comment by di-sukharev** [comment]
thank you @matscube 🙇

**Pull request merged**
