### PR TITLE
Re #190 - Fixing grammatical errors and enhancing overall grammar in README.md

### PR DESCRIPTION
**Pull request by avighnac**
This is an identical pull request to #190 without the lots of changes issue. This should be okay to merge.

This commit addresses grammatical errors found in the project's readme and improves its overall grammar.

Emphasizing the significance of proper grammar cannot be stressed enough when it comes to enhancing the presentation of a project. Today, I came across this GitHub repository in a news article and was intrigued by the concept. Therefore, I decided to explore the repository. To my disappointment, I discovered several grammatical errors in the README.md file. However, the advantage of open source is that I can rectify these errors myself relatively easily if they bother me.

Please inform me if any modifications are necessary.

### CODE REVIEW

**Review by jlopezlira — COMMENTED** [review]
LGTM! But I can't approve it. :( 

@di-sukharev 👀

**Comment by di-sukharev** [comment]
@avighnac sorry to be sooo late, was [winning top 1](https://dev.to/devteam/github-dev-2023-hackathon-winners-announced-236o) in github hackathon with OpenCommit :) 

thank you <3 let me take some time to review it, i should have time on the weekend

**Review by di-sukharev — APPROVED** [review]

**Comment by di-sukharev** [comment]
thank you <3

**Comment by avighnac** [comment]
No worries, and it's amazing that opencommit won in github's hackathon!

I'm just glad that it's finally over haha.

You're welcome!

**Pull request merged**
