### PR TITLE
feat: Add Input Token Limit Config Option

### PR DESCRIPTION
**Pull request by mattsalt123**
### Description
This pull request introduces a new feature to set the input token limit through a new config option, as well as refactoring the output max tokens configuration to align with this functionality. This enhancement enables users to leverage the expanded token limits of the latest GPT-4 turbo and GPT-3.5 models when using OpenCommit.

#### New Config Options
OCO_TOKENS_MAX_INPUT=<max model token limit (default: 4096)>
OCO_TOKENS_MAX_OUTPUT=<max response tokens (default: 500)>

This replaces the former OCO_OPENAI_MAX_TOKENS config option.

### CODE REVIEW

**Comment by covolution** [comment]
Any update?

**Review by jlopezlira — COMMENTED** [review]
LGTM

**Comment by mattsalt123** [comment]
@di-sukharev I can take a look into the resolving the conflicts if this is something we wanted to get merged to allow configurable input token limits now that GPT4 turbo is on master

**Comment by di-sukharev** [comment]
@mattsalt123 i see the conflicts solved, could you test this branch works as expected by building the source `npm run build` and running the js build `npm run start -- config set OCO_OPENAI_MAX_TOKENS=... && npm run start` this will run opencommit from the `/out` dir, not the globally installed version

**Comment by mattsalt123** [comment]
@di-sukharev Tested the branch successfully as above, all runs fine. Just to note however the OCO_OPENAI_MAX_TOKENS config option has been changed as per the PR description above:

**New Config Options**

OCO_TOKENS_MAX_INPUT=<max model token limit (default: 4096)>
OCO_TOKENS_MAX_OUTPUT=<max response tokens (default: 500)>

This replaces the former OCO_OPENAI_MAX_TOKENS config option.

The js build of the branch runs fine with these updated settings.

**Review by di-sukharev — APPROVED** [review]

**Pull request merged**
