### PR TITLE
Feat #226: Implement Confirm-Commit and Confirm-Push Flags for Improved User Experience

### PR DESCRIPTION
**Pull request by malpou**
In this pull request, we have introduced new functionality to streamline the user's interaction with the CLI tool. This enhancement focuses on two main aspects: committing and pushing actions, which can now be confirmed upfront with the use of flags.

**Changes:**
- _Update_ in cli.ts: Introduced confirmCommitFlag and confirmPushFlag as command-line flags. These flags provide a means for users to confirm commit and push actions at the start of the process. As a result, they will no longer need to confirm these actions manually each time they occur, greatly improving the user experience.
- _Enhancement_ in commit.ts: Added support for the newly introduced confirmCommitFlag and confirmPushFlag. If the flags are set to true, the commit and push actions proceed automatically without requiring user confirmation. If the flags are false or not provided, the user is prompted to confirm these actions. This modification ensures seamless integration of the new flags with existing functionalities.

We believe that this update will significantly improve the experience of our users by making the commit and push processes more streamlined and user-friendly.

Issue #226

### CODE REVIEW

**Comment by ionutz89** [comment]
Any update about this feature?

**Comment by malpou** [comment]
@ionutz89 Still waiting for someone to take a look at my PR

**Comment by dev-mtjoy** [comment]
+1

**Review by dev-mtjoy — COMMENTED** [review]
Looks good to me!

**Comment by dev-mtjoy** [comment]
@di-sukharev ?

**Comment by sebastienfi** [comment]
LGTM

**Review by sebastienfi — COMMENTED** [review]
LGTM

**Comment by di-sukharev** [comment]
will get to it soon <3

**Comment by di-sukharev** [comment]
@malpou what is the example to use it, is it like `oco --confirm-commit`?

**Comment by charanjit-singh** [comment]
Any update? Need this badly

**Comment by malpou** [comment]
> @malpou what is the example to use it, is it like `oco --confirm-commit`?

Yes, that's the though it was mentioned in an issue #226

**Comment by di-sukharev** [comment]
@malpou i dont think that so long message is really an optimal ux, i would go with a shorter flag like `oco -f` (make sure `-f` is not in git itself, i dont remember)

**Review by Christophe-Chantraine-djm-digital — COMMENTED** [review]
That sounds good for me

**Comment by Christophe-Chantraine-djm-digital** [comment]
> @malpou i dont think that so long message is really an optimal ux, i would go with a shorter flag like `oco -f` (make sure `-f` is not in git itself, i dont remember)

Agree with that, but what do you mean by "not in git itself" ? Are you talking about this command, for example: 
`git push **-f**` ? If yes, this param exists on the git push.

**Comment by di-sukharev** [comment]
@Christophe-Chantraine-djm-digital, yep i meant what you described, but i think if we do `oco --f` it would still be first processed by opencommit and we can manage the expected behaviour.

So, fixing the conflict, making the flags shorter (`--f` is good), then building `npm run build` and testing locally `npm start --f` should be all. I will merge when you are sure all is tested <3

**Comment by malpou** [comment]
The flags are suitable and tested now! @di-sukharev 

Notes:
- When testing you need to use ` npm start -- --cc --cp` else params are not parsed to our CLI tool.
- Flags in `cleye` can't be shorter than 2 chars.

**Comment by malpou** [comment]
@di-sukharev
Any blockers on this?

**Comment by di-sukharev** [comment]
@malpou im so sotty this got closed, do you want to merge it? if so — please solve the conflict and i will get to it asap

**Comment by di-sukharev** [comment]
@malpou i've solved the readme conflict, could you check im not missing anything please and lets merge it!

**Comment by di-sukharev** [comment]
@malpou please solve the conflicts, i will merge, test and ship in the next version

**Comment by di-sukharev** [comment]
:(

**Pull request closed without merging**
