### PR TITLE
Add Google Gemini LLM support

### PR DESCRIPTION
**Pull request by drewpayment**
OK, this has been long time coming. I also included a few other changes I hope you will consider: 

- **tsconfig.json** changes for better TypeScript support during development 
- **engine.ts** updated openai, ollama and gemini classes to be exported instead of instantiating instances of the classes. This will ensure that only the intended model is instantiated
- **OCO_API_KEY** added this environment variable with continued support for **OCO_OPENAI_API_KEY** so users are not confused when setting api key
- **gemini.ts** model support includes ability to use Gemini Pro 1.5 model, and will use better model completions from Gemini if the advanced model is chosen

### CODE REVIEW

**Comment by drewpayment** [comment]
@di-sukharev sorry for such a big delay but cleaned up the gemini output, added some extra features around Gemini Pro 1.5 and a few other small convenience things in project I hope you'll consider.

**Comment by di-sukharev** [comment]
pls target your PRs to dev

i've changed the base to dev from master, please solve the confilicts

**Comment by di-sukharev** [comment]
@drewpayment hi, pls let me know when i can merge it

**Comment by km-tr** [comment]
@drewpayment @di-sukharev When you did the force push last time, didn't the changes to Gemini disappear?

**Comment by drewpayment** [comment]
I took too long and there were a lot of conflicts. My fork is almost ready, started working on it last night to bring support to all the Google models. Just trying to finish the tests up before I resubmit the PR.

**Comment by drewpayment** [comment]
I added the new PR that merged to dev with tests included.

https://github.com/di-sukharev/opencommit/pull/349

**Pull request merged**
