### PR TITLE
LocalAI Integration

### PR DESCRIPTION
**Pull request by malpou**
This draft PR introduces support for integrating [LocalAI](https://github.com/go-skynet/LocalAI) into our application. Users who wish to run the LocalAI model locally can now do so with ease, leveraging the instructions and settings provided in our readme.

**Readme Additions:**

> #### Use LocalAI
> 
> We have added support to use [LocalAI](https://github.com/go-skynet/LocalAI) as a model. This is a free and open source model that you can run locally. To use this model, you need to have LocalAI running on your machine.
> 
> ##### Setup LocalAI
> This is the way our team configured our enviroment to run LocalAI. You can follow these steps here:
> 
> 1. Follow the [LocalAI Getting Started Example](https://localai.io/basics/getting_started/index.html)
> 2. Set the `OCO_OPENAI_BASE_PATH` to the path of your LocalAI instance. For example, if you are running LocalAI on port `8080`, you would set the `OCO_OPENAI_BASE_PATH` to `http://localhost:8080/v1`.
> 3. Set the `OCO_MODEL` to whatever model you're using following the getting started example the value will be `ggml-gpt4all-j`.
> 4. Now you can use OpenCommit with LocalAI!

**Notes:**
I am currently facing some challenges with the LocalAi container, so the full functionality has not been tested exhaustively. I'm trying to resolve the issue and awaiting a response from the team from LocalAi on what could be causing this issue.
Since I've just been following the guide in their documentation. [LocalAi Issue](https://github.com/go-skynet/LocalAI/issues/1019#issuecomment-1711683579)

But Local model support should be arriving soon.

Any contributions or feedback on this draft is highly welcome.

Issue #236

### CODE REVIEW

**Comment by di-sukharev** [comment]
@malpou you are superhero!

let me know when you are ready to test this and if any help is needed.

**Comment by malpou** [comment]
Will do, just waiting atm 😀

**Comment by jaroslaw-weber** [comment]
No activity? Could i work on itegrating ollama instead? I was able to make it work with another repo.
https://github.com/insulineru/ai-commit/pull/18/files

**Comment by intothemoonlite** [comment]
ollama is getting very popular! would be good to have

**Pull request closed without merging**
