### PR TITLE
fix(config.ts): invalid default config

### PR DESCRIPTION
**Pull request by izzybps**
Resolving #352 setting initial value of OCO_AZURE_ENDPOINT to undefined instead of '', where it causes errors while trying to set any other config upon initial installation.

### CODE REVIEW

**Comment by izzybps** [comment]
I made the pull request based on the guidelines of the CONTRIBUTING.md file and it generated this large amount of changes, the bug fix consists of one line change. If you need anything else feel free to ping me.
@di-sukharev

**Comment by edmilsonrobson** [comment]
Yeah, I recently installed oco and this was a very weird first experience

**Comment by di-sukharev** [comment]
i will test and merge this tomorrow, gonna be shipped in the next version

**Comment by minarc** [comment]
@di-sukharev I encountered the same issue after updating from version 3.0.1 to 3.1.2. Upon updating, the following environment variables are undefined:

```
OCO_OPENAI_API_KEY=api_key
OCO_ANTHROPIC_API_KEY=undefined
OCO_AZURE_API_KEY=undefined
OCO_GEMINI_API_KEY=undefined
OCO_TOKENS_MAX_INPUT=undefined
OCO_TOKENS_MAX_OUTPUT=undefined
OCO_OPENAI_BASE_PATH=undefined
OCO_GEMINI_BASE_PATH=undefined
OCO_DESCRIPTION=false
OCO_EMOJI=true
OCO_MODEL=gpt-4o-mini
OCO_LANGUAGE=en
OCO_MESSAGE_TEMPLATE_PLACEHOLDER=$msg
OCO_PROMPT_MODULE=conventional-commit
OCO_AI_PROVIDER=openai
OCO_GITPUSH=true
OCO_ONE_LINE_COMMIT=false
OCO_AZURE_ENDPOINT=undefined
OCO_TEST_MOCK_TYPE=commit-message
OCO_FLOWISE_ENDPOINT=:
OCO_FLOWISE_API_KEY=undefined
OCO_OLLAMA_API_URL=undefined
OCO_WHY=true
```
As a result, oco throws a type error related to max_token.

**Comment by di-sukharev** [comment]
this is definitely a bug, i fixed it in the new version, but its still not
deployed. for now please set the configs again

**Comment by rogerconsul-cw** [comment]
hey @di-sukharev 
just updated and the undefined value for OCO_TOKENS_MAX_OUTPUT is getting errors.
`400 Invalid type for 'max_tokens': expected an integer, but got a boolean instead.`

**Comment by di-sukharev** [comment]
gonna be fixed here https://github.com/di-sukharev/opencommit/pull/408

**Pull request merged**
