### PR TITLE
feat(config.ts): add OCO_MESSAGE_TEMPLATE_PLACEHOLDER configuration i…

### PR DESCRIPTION
**Pull request by seho-dev**
see #205

### CODE REVIEW

**Comment by seho-dev** [comment]
Tested local functionality

**Comment by seho-dev** [comment]
@di-sukharev

**Comment by di-sukharev** [comment]
sorry to be sooo late, was [winning top 1](https://dev.to/devteam/github-dev-2023-hackathon-winners-announced-236o) in github hackathon with OpenCommit :) 

will take a look

**Review by di-sukharev — APPROVED** [review]

**Comment by mreduar** [comment]
This does not work for me. When executing for example `oco 'MR2-1167: $message'` it gives an error.
```
➜ oco 'MR2-1167: $message'
│
┌  open-commit
│
◇  1 staged files:
│
◇  📝 Commit message generated
│
└  Commit message:
——————————————————
MR2-1167: fix(Invoice.php): add 'discount' attribute to the $appends array to include it in the model's attributes

The 'discount' attribute was missing from the $appends array in the Invoice model, causing it to not be included in the model's attributes. This fix adds the 'discount' attribute to the $appends array, ensuring that it is included in the model's attributes.
——————————————————

│
│
◇  📝 Commit message generated
│
└  ✖ Command failed with exit code 1: git commit -m MR2-1167: fix(Invoice.php): add 'discount' attribute to the $appends array to include it in the model's attributes

The 'discount' attribute was missing from the $appends array in the Invoice model, causing it to not be included in the model's attributes. This fix adds the 'discount' attribute to the $appends array, ensuring that it is included in the model's attributes. MR2-1167: $message
error: pathspec 'MR2-1167: $message' did not match any file(s) known to git
```

I have already configured `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` in different ways and it does not work.

**Comment by EcomGraduates** [comment]
> This does not work for me. When executing for example `oco 'MR2-1167: $message'` it gives an error.
> 
> ```
> ➜ oco 'MR2-1167: $message'
> │
> ┌  open-commit
> │
> ◇  1 staged files:
> │
> ◇  📝 Commit message generated
> │
> └  Commit message:
> ——————————————————
> MR2-1167: fix(Invoice.php): add 'discount' attribute to the $appends array to include it in the model's attributes
> 
> The 'discount' attribute was missing from the $appends array in the Invoice model, causing it to not be included in the model's attributes. This fix adds the 'discount' attribute to the $appends array, ensuring that it is included in the model's attributes.
> ——————————————————
> 
> │
> │
> ◇  📝 Commit message generated
> │
> └  ✖ Command failed with exit code 1: git commit -m MR2-1167: fix(Invoice.php): add 'discount' attribute to the $appends array to include it in the model's attributes
> 
> The 'discount' attribute was missing from the $appends array in the Invoice model, causing it to not be included in the model's attributes. This fix adds the 'discount' attribute to the $appends array, ensuring that it is included in the model's attributes. MR2-1167: $message
> error: pathspec 'MR2-1167: $message' did not match any file(s) known to git
> ```
> 
> I have already configured `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` in different ways and it does not work.

I can confirm this bug. It's happening to me as well I tried oco '$msg #someticketnumber' as well as '#some ticket number $msg'

same error

**Comment by di-sukharev** [comment]
will take a look now

**Comment by di-sukharev** [comment]
well this code doesnt account for a single commit message e.g. like this:
```
chore(README.md): update OCO_DESCRIPTION and OCO_EMOJI variable descriptions for OpenCommit config
feat(README.md): add OCO_MODEL variable description for OpenCommit config
fix(README.md): update OCO_MESSAGE_TEMPLATE_PLACEHOLDER and OCO_PROMPT_MODULE variable descriptions for OpenCommit config
```

it appends $msg in the very first line like this:
```
MSG_HERE: chore(README.md): update OCO_DESCRIPTION and OCO_EMOJI variable descriptions for OpenCommit config
feat(README.md): add OCO_MODEL variable description for OpenCommit config
fix(README.md): update OCO_MESSAGE_TEMPLATE_PLACEHOLDER and OCO_PROMPT_MODULE variable descriptions for OpenCommit config
```

im not sure if this really helps, so lets see how this PR manages the same problem #160

**Pull request merged**
