### PR TITLE
Adding support for flowise as an AI provider 

### PR DESCRIPTION
**Pull request by JMN09**
Modified command/config.ts to support OCO_FLOWISE_ENDPOINT and OCO_FLOWISE_API_KEY.
Added a class FlowiseAi that implements AiEngine 
Modified utils/engine.ts to take into account the provider being flowise

Closes (#373)

### CODE REVIEW

**Comment by di-sukharev** [comment]
hi @JMN09, thanks for your contribution!

i see the branch has conflicts, could you change the base branch to master please?

**Comment by JMN09** [comment]
Hello @di-sukharev, hope you're doing well

I merged from master, do you still see any conflicts ?

**Comment by di-sukharev** [comment]
Screenshot 2024-08-14 at 14 10 28

i see this

**Comment by JMN09** [comment]
Hey again,
I fixed the merge conflicts, there shouldn't be any merge issues anymore, please confirm.

**Comment by di-sukharev** [comment]
thank you for your contribution, it will be released with with a new build

**Pull request merged**
