### PR TITLE
add support for Azure OpenAI API - continue MR 167

### PR DESCRIPTION
**Pull request by ByJacob**
Since I didn't see any changes being made in MR https://github.com/di-sukharev/opencommit/pull/167, I decided to synchronize the main branch with @takuya-o changes.
In addition, I ran `prettier` on the code

### CODE REVIEW

**Comment by ByJacob** [comment]
@di-sukharev

**Comment by di-sukharev** [comment]
gonna get to it soon <3

**Comment by di-sukharev** [comment]
pls fix tests

**Comment by ByJacob** [comment]
> pls fix tests

done

**Review by di-sukharev — APPROVED** [review]

**Pull request merged**
