### PR TITLE
Support Gitmoji Format in Commit Messages

### PR DESCRIPTION
**Pull request by malpou**
This PR modifies opencommit to better support the Gitmoji convention, ensuring compatibility with projects that currently use Gitmoji.

**Changes**

- Added a utility method in `removeConventionalCommitWord.ts` to adjust the commit format according to the Gitmoji guidelines.

- Updated `prompts.ts` to dynamically generate prompts based on whether the `OCO_EMOJI` configuration option is enabled. When enabled, prompts will guide users to follow the Gitmoji format.

**Notes**
I'm unsure if this is the best approach to implement Gitmoji support. Specifically:

- The changes may add too many tokens to each request.
- There's a potential for simplifying the list by removing less commonly used emojis.

Issue #239 

Feedback is much appreciated!

Best regards
@malpou

### CODE REVIEW

**Comment by shkreios** [comment]
Hi @malpou, I've tested your PR locally, and it does enhance the specificity of GPT's emoji output, moving away from the constant use of 🔧. However, it seems to have lost the prefixing of messages with tags like `fix`, `chore`, etc.

Additionally, the increased token count due to the inclusion of various emojis and explanations may not be universally beneficial. Perhaps a flag to toggle this feature on a per-commit basis could be a worthwhile addition. What do you think?

**Comment by malpou** [comment]
Thanks for looking at it @shkreios 

The loss of `fix`, `chore`, etc, is done on purpose.
This is due to the changes on src/prompts.ts:143-144.

As my understanding the `fix` & `chore` are keywords in **Conventional Commits** and not present in the **GitMoji** standard.

Quote from issue:

> In the context of Gitmoji, the emoji already provides enough context as to what the commit is about. Titles should also use sentence case.

**If it should be a flag I'm not sure:**

I think these changes are moving us closer to having two options of commit messages one being **Conventional Commits** and the other being **GitMoji**.

Then the `OCO_EMOJI` configuration will be the opt-in toggle to use **GitMoji** instead of **Conventional Commits**.

Let me hear your thoughts 😄 

cc: @stalinkay & @di-sukharev

**Comment by shkreios** [comment]
Hey @malpou,

> As my understanding the fix & chore are keywords in Conventional Commits and not present in the GitMoji standard.

Understood, and it's logical to align with the Conventional Commits standard. While I personally preferred the prior commit style, the standard takes precedence.

> If it should be a flag I'm not sure:

My primary concern is the frequent need to switch between `gpt-4` and `gpt-3.5-turbo-16k` due to token limits. This impacts whether I can effectively utilize the CLI for certain commits. A substantial increase in the base prompt length often proves counterproductive in my specific cases.

**Comment by malpou** [comment]
I just had an idea, What if we select a few standard emojis from GitMoji and always add these to the emoji prompts.

Then I'll add a flag you can include if you want ALL of the GitMoji emojis.

Toughts?

**Comment by malpou** [comment]
The flag could be called '--f-gms' for **Full GitMoji Spec**

**Comment by malpou** [comment]
This is the list of emojis i would prioritize:

- 🐛, Fix a bug;
- ✨, Introduce new features;
- 📝, Add or update documentation;
- 🚀, Deploy stuff;
- ✅, Add, update, or pass tests;
- ♻️, Refactor code;
- ⬆️, Upgrade dependencies;
- 🔧, Add or update configuration files;
- 🌐, Internationalization and localization;
- 💡, Add or update comments in source code;

**Comment by malpou** [comment]
@shkreios there is new stuff to look at whenever you have time 😄

**Comment by malpou** [comment]
@di-sukharev
Any blockers on this?

**Comment by shkreios** [comment]
> 
@shkreios there is new stuff to look at whenever you have time 😄

Sorry i was currently busy i try to have a look thx week thank you

**Comment by di-sukharev** [comment]
will test and merge

**Comment by di-sukharev** [comment]
@malpou i've resolved the readme conflict, have you tested this PR by building `npm run build && npm run start -- <flags>`? I will also try to get to it while you are busy

**Review by di-sukharev — APPROVED** [review]

**Pull request merged**
