### PR TITLE
Add Groq AI support.

### PR DESCRIPTION
**Pull request by ozeliurs**
Following comments in #346, I set up groq support with the `OCO_GROQ_API_KEY` variable by setting the OCO_AI_PROVIDER to groq.

I am not very familiar with this project, so please feel free to point out mistakes.

### CODE REVIEW

**Comment by di-sukharev** [comment]
how do you pay for the groq api key?

**Comment by ozeliurs** [comment]
> how do you pay for the groq api key?

it is free brother, no need to pay.

Go to https://console.groq.com/keys, create an account and generate an api key.

**Comment by di-sukharev** [comment]
hmm.. do they then somehow log your requests or they dont explicitly tell how requests privacy is managed?

**Comment by ozeliurs** [comment]
don't know, all I found is this: https://wow.groq.com/privacy-policy/

They say they don't retain our data but they have to keep count on how much request we make so they for sure log something.

**Comment by di-sukharev** [comment]
thank you! @ozeliurs please fix the conflicts, sorry for that, just released 3.0.18 🥵

**Comment by ozeliurs** [comment]
> thank you! @ozeliurs please fix the conflicts, sorry for that, just released 3.0.18 🥵

Should I switch to dev before ?

**Comment by di-sukharev** [comment]
dev is best, yes

**Comment by ozeliurs** [comment]
Updated to be able to be merged to dev :)

**Comment by di-sukharev** [comment]
there was a refactoring https://github.com/di-sukharev/opencommit/pull/391, please fix conflicts

**Comment by di-sukharev** [comment]
you will also need to adjust your code a bit, it will be easier to support

**Comment by di-sukharev** [comment]
@ozeliurs i have resolved the conflicts, but you still need to change the GroqAiEngine a bit, it's simple, please take a look at any other Engine implementation, e.g. OpenAiEngine.

Every Engine is now taking parameters in the constructor, i passed them to your `new GroqAi(here)` call, but you need to add the constructor anyway

**Comment by di-sukharev** [comment]
@ozeliurs

**Comment by di-sukharev** [comment]
please follow any aiEngine (e.g. OpenAiEngine) implementation in this [file](https://github.com/di-sukharev/opencommit/blob/8ae927e2dc5a5b252ffe9adef7143cb7b11202c8/src/utils/engine.ts#L11), there are few more lines to add to the PR so we can merge it @ozeliurs

**Comment by ozeliurs** [comment]
Hi,

I made the modifications according to your refactoring. The code works now by setting:
- `OCO_AI_PROVIDER='groq'`
- `OCO_API_KEY=<groq_api_key>`
- `OCO_MODEL=llama3-70b-8192` (or any available model)

**Comment by di-sukharev** [comment]
awesome @ozeliurs, thanks for the contribution, tests are passing, merging it, gonna be available in the next release

**Review by di-sukharev — APPROVED** [review]

**Comment by ozeliurs** [comment]
Thanks a lot, pleasure contributing. :)

**Comment by erickedji** [comment]
This will still fail in src/migrations/00_use_single_api_key_and_url.ts#L35 because the switch doesn't handle groq.

**Pull request merged**
