### PR TITLE
Remove oc alias and update OpenCommit CLI to use 'oco'

### PR DESCRIPTION
**Pull request by Moulick**
oc is a pretty well-known alias for OpenShift CLI

---
Closes https://github.com/di-sukharev/opencommit/issues/144

### CODE REVIEW

**Review by di-sukharev — APPROVED** [review]

**Comment by Moulick** [comment]
Didn't realize that I should have forked from the `dev` branch. Rebased on `dev` now

**Comment by Moulick** [comment]
@di-sukharev anything pending?

**Comment by di-sukharev** [comment]
@Moulick hi, sorry for being late :) was busy,

I see some conflicts are here to be fixed

**Comment by Moulick** [comment]
The branch history got confusing, making a new PR

**Comment by Moulick** [comment]
superseded by https://github.com/di-sukharev/opencommit/pull/178

**Pull request closed without merging**
