### PR TITLE
feat(api.ts): add support for OPENAI_BASE_PATH configuration variable

### PR DESCRIPTION
**Pull request by kimlym**
feat(config.ts): add OPENAI_BASE_PATH configuration key and validator function

### CODE REVIEW

**Review by cforce — APPROVED** [review]

**Comment by fabwamb** [comment]
@kimlym  Did you also paid attention to the validation of OPENAI_API_KEY which doesn't seems to allow Azure OpenAI apoi keys as they don't follow the pattern "sk-" being used at Openai itself. The validation shall be turned of at least when OPENAI_BASE_PATH is overwritten.

error message is "Unsupported config key OPENAI_API_KEY: Must start with "sk-" when using an Azure Openai API -key
This validations are not done e.g when using python openai module and the api client still works/compatible, i assume juts not validating is ok.

**Comment by joberror** [comment]
There

> @kimlym Did you also paid attention to the validation of OPENAI_API_KEY which doesn't seems to allow Azure OpenAI api keys as they don't follow the pattern "sk-" being used at Openai itself. The validation shall be turned of at least when OPENAI_BASE_PATH is overwritten.
> 
> error message is "Unsupported config key OPENAI_API_KEY: Must start with "sk-" when using an Azure Openai API -key This validations are not done e.g when using python openai module and the api client still works/compatible, i assume juts not validating is ok.

Yes, that error comes up when the key doesn't match that of OPENAI.

**Comment by cforce** [comment]
You seem to missundertand
> opencommit — config 1234545678989
│
└  ✖ Unsupported config key OPENAI_API_KEY: Must start with "sk-"

Auzure OpenAI keys' don't start with "sk-"

**Comment by tifandotme** [comment]
what does OPENAI_BASE_PATH do exactly?

**Comment by kimlym** [comment]
> @kimlym Did you also paid attention to the validation of OPENAI_API_KEY which doesn't seems to allow Azure OpenAI api keys as they don't follow the pattern "sk-" being used at Openai itself. The validation shall be turned of at least when OPENAI_BASE_PATH is overwritten.
> 
> error message is "Unsupported config key OPENAI_API_KEY: Must start with "sk-" when using an Azure Openai API -key This validations are not done e.g when using python openai module and the api client still works/compatible, i assume juts not validating is ok.

I wasn't aware of Azure also has an OpenAPI endpoint, however the purpose of this PR is merely to add the ability to override base path so the rest is a little bit out of scope for this PR. You do have a point of better error handling and usage instruction, could be added later

**Comment by cforce** [comment]
For me it still not working, because of the validation which alwa fails in azure openai

**Pull request merged**
