### PR TITLE
feat: Add all of OpenAI GPT models

### PR DESCRIPTION
**Pull request by XiaomaiTX**
including #363 but add all of OpenAI GPT models

### CODE REVIEW

**Comment by XiaomaiTX** [comment]
Need to be review

Best regards.

**Comment by di-sukharev** [comment]
Will do today

**Review by di-sukharev — APPROVED** [review]

**Comment by di-sukharev** [comment]
@XiaomaiTX thank you for help, if you would have time in the future — could you consider removing all the models are allowing any string? this would allow us to use any model when it's announced without adding it to the config :)

**Comment by XiaomaiTX** [comment]
Hi, @di-sukharev

refer to: #365

Best regards.

**Pull request merged**
